ecommerce_project/cart_app/urls.py
from  django.urls import path

from . import views

app_name='cart'

urlpatterns=[
    path('',views.card_detail,name='cartdetail'),
    path('add/<int:product_id>/',views.add_cart,name='addcart'),
    path('remove/<int:product_id>/',views.cart_remove,name='removecart'),
    path('delete/<int:product_id>/',views.full_delete,name='fulldelete')
]

ecommerce_project/ecomapp/urls.py
from django.urls import path

from ecomapp import views
app_name='ecomapp'

urlpatterns = [

    path('',views.allProducts,name='allproducts'),
    path('<slug:c_slug>/',views.allProducts,name='product_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/',views.proDetail,name='prodetail'),
]

ecommerce_project/ecomproject/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls.static import  static

from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom/',include('ecomapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart_app.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

ecommerce_project/search_app/urls.py
from django.urls import path
from .import views
app_name='search_app'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult')
]

ecommerce_project/cart_app/models.py
from ecomapp.models import Product,Category
from django.db import models

# Create your models here.

class Cart(models.Model):

    cart_id=models.CharField(max_length=200,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table="Cart"
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'


    def sub_total(self):
        return  self.product.price * self.quantity

    def __str__(self):
        return self.product.name

ecommerce_project/ecomapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)
    img=models.ImageField(upload_to='category',blank=True)
    desc=models.TextField(blank=True)
    slug=models.SlugField(max_length=200,unique=True)

    def get_url(self):
        return reverse('ecomapp:product_by_category',args=[self.slug])
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
            return  self.name

class Product(models.Model):
    name=models.CharField(max_length=200,unique=True)
    slug=models.SlugField(max_length=200,unique=True)
    desc=models.TextField()
    img=models.ImageField(upload_to='products',blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)


    def get_detail(self):
        return reverse('ecomapp:prodetail',args=[self.category.slug,self.slug])
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return self.name

ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecomapp.models import Product
from cart_app.models import Cart,CartItem
from  django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def cartId(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cartId(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=cartId(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity <cart_item.product.stock:

            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cartdetail')

def card_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cartId(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cartId(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cartdetail')

def full_delete(request,product_id):
    cart=Cart.objects.get(cart_id=cartId(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cartdetail')

ecommerce_project/ecomapp/views.py
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from django.shortcuts import render, get_object_or_404
from .models import  Category,Product
# Create your views here.
# def index(request):
#     return  HttpResponse('index')

def allProducts(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)

        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)

    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':products})


def proDetail(request,c_slug,p_slug):
    try:

        product=Product.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerce_project/search_app/views.py
from django.shortcuts import render
from ecomapp.models import  Product
from django.db.models import Q
# Create your views here.

def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerce_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
    <!-- CSS only -->
 <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;1,300&family=Noto+Sans+JP:wght@300&family=Roboto&display=swap" rel="stylesheet"></head>
    <script src="https://kit.fontawesome.com/c575cd804e.js" crossorigin="anonymous"></script>
<body>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
<!-- JavaScript Bundle with Popper -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>
</html>

ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

This is the cart page


{% endblock %}

{% block title %}

Cart

{% endblock %}


{% block content %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <h2 class="text-center my_title">
            Your shopping cart is empty
        </h2>
        <br>
        <p> <a href="{% url 'ecomapp:allproducts' %}">Please click here to continue</a> </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <h2 class="text-center my_title">
            Your Shopping Cart
        </h2>
    </div>
</div>
{% endif %}

<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_table">
            <thead class="my_head">
            <tr>
                <th colspan="5">
                    Your items
                </th>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr><td class="text-left"><a href="">
                <img src="{{cart_item.product.img.url}}" class="float-left rounded custom_image" style="width:50px;height:50px;">
            </a> </td>
          
            <td>{{cart_item.product.name}}
            <br>
                SKU : {{cart_item.product.id}}
                <br>
                Price :Rs {{cart_item.product.price}}
                <br>
                Quantity: {{cart_item.quantity}} x $ {{cart_item}}
            </td>
               <td>
                   Rs {{cart_item.sub_total}}
               </td>
                {% if cart_item.quantity < cart_item.product.stock %}

                <td>
                  <a href="{% url 'cart:addcart' cart_item.product.id %}" class="custom_a">
                    <i class="fa-solid fa-plus custom_icon"> </i></a>
                   &nbsp; &nbsp;<a href="{% url 'cart:removecart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                   &nbsp;&nbsp;<a href="{% url 'cart:fulldelete' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>


                    &nbsp;&nbsp;<a href="{% url 'cart:removecart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                   &nbsp;&nbsp;<a href="{% url 'cart:fulldelete' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="my_table">
            <thead class="my_head">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                   Please review your shopping cart items before proceeding with the order
                    payment.
                </td>
            </tr>
            <tr style="margin-top:20px; border-spacing: 10px 5px;">
                <td style="margin-top:20px;font-size:15px;">
                    Total  : <strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
    <div class="text-center">
        <a href="{% url 'ecomapp:allproducts' %}" class="btn btn-block btn-secondary my_button">
            Continue Shopping
        </a>

          <a href="{% url 'ecomapp:allproducts' %}" class="btn btn-block btn-primary my_button">
            Payment Processing
        </a>
    </div>

</div>

{% endblock  %}

<!--/*** {{cart_item.product.get_absolute_url ***-->

ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
{{ category.description|truncatewords:150 }}
{% else %}
Welcome to JJJ Store
{% endif %}
{% endblock %}

{% block title %}
{% if category %}
{{ category.name }}- JJJ store
{%  else %}
See our new collections
{% endif %}
{% endblock %}


{% block content %}
<div class="container-fluid">
{% if category %}

<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">

    <div>
        <p class=" text-center"><a class="category-head" href="{% url 'ecomapp:allproducts' %}">Our Product Collections</a> </p>

    </div>
</div>
{% endif %}
<div class="col-12 col-md-12 col-lg-12">
    {% if category %}
    <div class="text-center" >
        <img class="" src="{{category.img.url}}" alt="{{category.name}}" style="width:100%;height:400px;">
    </div>

<br>

<div style="margint-top:30px;">
    <h1 class="text-center">{{category.name}}</h1>
    <h3 class="text-center">{{category.description}}</h3>
</div>
</div>
{% else %}
</div>
</div>


    <div style="width:100%;">
<div>
    <img src="{% static 'bannet.png' %}" style="width:100%;height:500px;">
    <p>dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
</div>
{% endif %}

<div class="container">
<div class="row">


    {% for product in products.object_list %}

<div class="col-12 col-sm-6 col-md-4 col-lg-4" >
        <div class="card" style="width: 18rem;margin-top:2em;">
            <a href="{{product.get_detail}}">
            <img class="card-img-top product_image" src="{{product.img.url}}" alt="{{product.name}}">
                </a>
            <div class="card-body">
             <h2 class="card-title text-center">{{product.name}}</h2>
            <h5 class="card-text text-center">Rs {{product.price}}</h5>
  </div>
</div>
</div>
    {% endfor %}


    <div style="margin-top:30px;">
        {% if products.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-sm btn-light {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {%  endfor %}
        </div>
        {% endif %}
        <br>
    </div>
</div>

</div>
{% endblock %}

ecommerce_project/templates/footer.html
<div class="container-fluid">
<div class="footer navbar-fixed-bottom my-footer">
  <h5 class="text-center">
    Ⓒ copyright JJJ Company Limited--
  </h5>
</div>
  </div>

ecommerce_project/templates/header.html
{% load static %}
<header>
  <center>
      <a href="{% url 'ecomapp:allproducts' %}" ><img src="{% static 'j.png' %}" alt="logo" style="width:200px;"></a>
  </center>
</header>

ecommerce_project/templates/navbar.html
<div class="" style="width:100%;">
    <nav class="navbar navbar-expand-lg navbar-light bg-dark p-2">
        <a class="navbar-brand white" href="#">JJJ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link active white" href="{% url 'ecomapp:allproducts' %}" style="color:white;">Home </a>
                </li>

                <li class="nav-item dropdown {% if 'ecomapp' in request.path %}active{% endif %}">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown"  aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color:black;">

                        <li><a class="dropdown-item white" href="{% url 'ecomapp:allproducts' %}">All Products</a></li>

                        {% for cat in links %}
                        <li><a class="dropdown-item white" href="{{cat.get_url}}">{{cat.name}} </a></li>
                        {% endfor %}

                    </ul>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item active">
                    <a class="nav-link white" href="{% url 'cart:cartdetail' %}"> <i class="fa-solid fa-cart-shopping">(
                        {{item_count}} )</i></a>
                </li>
                {% endif %}
            </ul>

            <form class=" form-edit form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}"
                  method="get">
                {% csrf_token %}
                <input class="form-control mr-sm-2 " style='margin-left:30em;' type="search" placeholder="Search"
                       aria-label="Search" name="q">
                <button class="btn btn-outline-danger my-2 my-sm-0 white" style='margin-left:3em;background-color:red;' type="submit"><i
                        class="fa-sharp fa-solid fa-magnifying-glass"></i></button>
            </form>
        </div>
    </nav>
</div>

ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{{ product.description|truncatewords:150 }}


{% endblock %}

{% block title %}

{{ product.name }}

{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
    <div class="">
        <p><a href="{% url 'ecomapp:allproducts' %}">Home</a>
            |<a href="{{product.category.get_url}}">{{product.name}}</a>
        </p>

    </div>
</div>
</div>
<br>
<div class="container">
    <div class="row">
    <div class="col-12 col-sm-12 col-md-6 col-lg-6">
        <img src="{{product.img.url}} " alt="{{product.name}}" style="min-width:18rem;width:10rem;">
        <div>

        </div>  </div>

        <div class="col-12 col-sm-12 col-md-6 col-lg-6">
            <div>
                <h1>{{product.name}}</h1>
                <p>${{product.price}}</p>
                <p style="font-size:20px;"> Description</p>
                <p>{{product.desc}}</p>
                {% if product.stock <= 0 %}
                <p><b>Out of stoct</b></p>
                {% else %}
                <p><a class="btn btn-success" href="{% url 'cart:addcart' product.id %}">Add to cart</a></p>
                {% endif %}

        </div>
    </div>
</div>
</div>
{% endblock %}

ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

Your search results


{% endblock %}

{% block title %}

Search result

{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <p class="text-center my_search_text">You have searched for : "{{query}}"</p>
    </div>




<div class="row">





    {% for product in products %}
        <div class="card" style="width: 18rem;margin-top:2em;margin-left:3em;">
            <a href="{{product.get_detail}}">
            <img style=" width:15rem;" class="card-img-top product_image" src="{{product.img.url}}" alt="{{product.name}}">
                </a>
            <div class="card-body">
             <h2 class="card-title text-center">{{product.name}}</h2>
            <h5 class="card-text text-center">Rs {{product.price}}</h5>
            </div>
        </div>
        {% empty %}
            <div>
    <p class="text-center my_search_text">0 results found"</p>
            </div>
     {% endfor %}



</div>
  </div>
{% endblock %}